### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg-cli#125]
- Testing requires a running mreg server. Write scripts for setup/teardown
   - Start with an empty database or some predefined content?
- Determine if the old test files `setup_test` and `teardown_test` are usable
- Add configuration for Travis CI

**Comment by paalbra** [comment]
Or just mock data for simple testing?

**Comment by oyvindhagberg** [comment]
This was resolved and merged to master in https://github.com/unioslo/mreg-cli/commit/30e136eea0d13493dae9594d3d9e4a756a891518.
