### ISSUE TITLE
`host a_change` doesn't work if the current ip address has an associated mac address

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg-cli#131]
Not sure if this is due to a bug in mreg-cli, mreg, or if it just hasn't been implemented.
In any case, I think the command should work, so I have classified this issue as a bug.

When looking into this, also check if `aaaa_change` behaves the same way.

**Comment by mbakke** [comment]
Fixed in https://github.com/unioslo/mreg/pull/416.
