### ISSUE TITLE
host txt_remove doesn't properly encode parameters

### ISSUE THREAD

**Issue by paalbra** [unioslo/mreg-cli#134]
```
mreg> host txt_add host.example.com 'asdf;asdf'
OK: : Added TXT record to host.example.com
mreg> host txt_remove host.example.com 'asdf;asdf'
WARNING: : host.example.com has no TXT records equal: asdf;asdf
```

`txt_remove` tries to get the record by sending `txt=asdf;asdf`. This does not work. `txt=asdf%3Basdf` would work.

Proper encoding is needed:

https://github.com/unioslo/mreg-cli/blob/aa0552d01b31a6da549fb7014cd467e6386c545a/mreg_cli/host.py#L2775-L2780

**Comment by paalbra** [comment]
To elaborate:

The obvious quick and dirty fix is to encode at line 2777.

A proper fix would be to pass parameters (params dict) down to requests and let that library deal with encoding (it's called "HTTP for Humans" after all).

Looks like a refactor might interfere with both the mocktraffic and history part of the code though. Does the history part even do anything? I'm not familiar with the mocktraffic part.

**Comment by paalbra** [comment]
Regarding history #135

**Comment by mbakke** [comment]
@paalbra Do you want to submit a PR for the quick and dirty fix?

I'm looking into a larger refactor, but am not terribly familiar with mreg-cli yet and need more time to study and experiment.

**Comment by paalbra** [comment]
I don't think there is any reason to do the quickfix. This doesn't seem to produce a lot of problems/be a common problem.

I've pushed a WIP for a proper fix: https://github.com/unioslo/mreg-cli/tree/fix-134-wip . It resolves this issue.

```
TEST> host info host.example.com
Name:         host.example.com
Contact:
A_Records     IP              MAC
              192.168.0.101   <not set>
TTL:          (Default)
TEST> host txt_add host.example.com 'asdf;asdf'
OK: : Added TXT record to host.example.com
TEST> host info host.example.com
Name:         host.example.com
Contact:
A_Records     IP              MAC
              192.168.0.101   <not set>
TTL:          (Default)
TXT:          asdf;asdf
TEST> host txt_remove host.example.com 'asdf;asdf'
OK: : deleted TXT records from host.example.com
TEST> host info host.example.com
Name:         host.example.com
Contact:
A_Records     IP              MAC
              192.168.0.101   <not set>
TTL:          (Default)
```

However:

1. mocktraffic and tests should be looked into. I think @oyvindhagberg merged those parts.
2. Every call to the util functions that make use of parameters should be converted to use the new params parameter

**Comment by paalbra** [comment]
... and the history part can be ignored. It should be removed as stated in #135

**Comment by paalbra** [comment]
>     2. Every call to the util functions that make use of parameters should be converted to use the new params parameter

Commited https://github.com/unioslo/mreg-cli/commit/cd79c95c904cd85619d9df2fc9e7f60ecf70a5b5

**Comment by paalbra** [comment]
>     1. mocktraffic and tests should be looked into. I think @oyvindhagberg merged those parts.

I'm pretty sure a PR could be made from `fix-134-wip` if this gets resolved.

**Comment by paalbra** [comment]
This might do the trick? https://github.com/unioslo/mreg-cli/commit/1a2e3fef7bd1afeebedc5c83485212cf4f0ba100

Passing:
https://travis-ci.org/github/unioslo/mreg-cli/builds/745220057

I'm not familiar with the travis and mocktraffic part though...
