### ISSUE TITLE
What is history.py?

### ISSUE THREAD

**Issue by paalbra** [unioslo/mreg-cli#135]
Does history.py do anything? Could/should it be removed?

I can't tell if it's in use after a quick look. Might be used by prompt_toolkit somehow?

**Comment by oyvindkolbu** [comment]
Old and incomplete attempt to track commands entered by the user, in order to revert actions. I'd say it should be removed entirely, and a `undo`-command or similar should instead rely on the history data stored in mreg.

Removing `history.py` will clean up a lot of uneeded code.

**Comment by terjekv** [comment]
Removed in https://github.com/unioslo/mreg-cli/pull/191.
