### ISSUE TITLE
Let you assoc a MAC to a host with 1 IPv4 + 1 IPv6 by supplying hostname

### ISSUE THREAD

**Issue by oyvindhagberg** [unioslo/mreg-cli#141]
When checking if a machine has several IP addresses to make an assoc here: https://github.com/unioslo/mreg-cli/blob/05011b15ff4b964acb3b2c12114e0df9d3920a32/mreg_cli/dhcp.py#L32 then both IPv4 and IPv6 addresses are counted. A machine that has one IPv4 address and one IPv6 address is then told to do an assoc on IP and not name. Should we create a special case for this situation and make it associate with the same MAC?

**Comment by paalbra** [comment]
If this is implemented you should probably check that they're on the same VLAN.

**Comment by terjekv** [comment]
Hm, how would we ensure that both adresses are on the same VLAN? Are we guaranteed that VLAN identifiers are identical between IP spaces?
