### ISSUE TITLE
New command "network find"?

### ISSUE THREAD

**Issue by paalbra** [unioslo/mreg-cli#144]
It's hard to get a overview of networks. It would be nice to e.g. list networks on a given vlan.

Maybe add a "network find" command? Kind of like the "host find" command.

Possible search parameters that would be nice to have: category, location, vlan. Other/more?

https://github.com/unioslo/mreg/blob/75011f1b5a3e9b80a4a15d9a666c15a39f2ee160/mreg/models.py#L481-L489

**Comment by oyvindhagberg** [comment]
This was done in https://github.com/unioslo/mreg-cli/pull/159.
