### ISSUE TITLE
Add list of policies to host info output

### ISSUE THREAD

**Issue by safeaim** [unioslo/mreg-cli#155]
Host info should return list of policies for a host, as that is information users often want.

**Comment by paalbra** [comment]
I'm leaning towards this being a good idea, even though hostpolicy and mreg is two different parts.

Pro: Convenience/often wanted by the user
Con: Superfluous requests if you really just want host info
Con: Might be verbose if there are very many policies

I think the convenience outweighs the cons. Happy to hear other thoughts.

PS. Or maybe this could be triggered by a parameter flag? Like `host info -policy myhost.example.com`

**Comment by oyvindhagberg** [comment]
I agree with @paalbra, but I'd like to skip the parameter flag and just return the information by default.
