### ISSUE TITLE
Excluded addresses not counted correctly

### ISSUE THREAD

**Issue by lhakedal** [unioslo/mreg-cli#196]
Running "network info <network>" on a network with excluded addresses miscalculates the number of excluded addresses.

[...]
Excluded ranges:         15 ipaddresses
                        10.0.0.4 -> 10.0.0.19
[...]

Maybe here 
"def format_network_excluded_ranges(info: Dict[str, Any], padding: int = 25) -> None:"  
in 
https://github.com/unioslo/mreg-cli/blob/339857f7d3cd91e8cace132863a101317a68b778/mreg_cli/network.py#L71

**Comment by terjekv** [comment]
I'm think the solution is as simple as to always add one to the count of excluded IPs to cover the case of including the last IP in the range. Right now we only do it when the IPs are the same, but we get the same lack of inclusivity of the last IP no matter the range of the subtraction. https://github.com/unioslo/mreg-cli/blob/339857f7d3cd91e8cace132863a101317a68b778/mreg_cli/network.py#L71-L85.

**Comment by oyvindkolbu** [comment]
Yeah, looks trivial.

```
@@ -76,9 +76,7 @@ def format_network_excluded_ranges(info: Dict[str, Any], padding: int = 25) -> N
     for i in info:
         start_ip = ipaddress.ip_address(i["start_ip"])
         end_ip = ipaddress.ip_address(i["end_ip"])
-        count += int(end_ip) - int(start_ip)
-        if end_ip == start_ip:
-            count += 1
+        count += int(end_ip) - int(start_ip) + 1
     manager = OutputManager()
```
